    /*
    npm run start
    node src/expressApp.js
    */

    /* 
    App.js
        Toolbar.js
            CarList3.js
            TypeList.js
                SpecificCar.js
                    SpPic.js
                    SpMenu.js
                    SpNav.js
                        SpMotorisierung.js
                            MotorisierungInfos.js
                                ConsumptionLabel.js
                        SpLinesPakete.js
                            ShowDetails.js
                            Mietumfang.js
                        SpFarbenRaeder.js
                            ShowDetails.js
                            Mietumfang.js
                        SpPolsterZierelemente.js
                            ShowDetails.js
                            Mietumfang.js
                        SpAusstattung.js
                            ElementSearch.js
                            ShowDetails.js
                            Mietumfang.js
                        SpMeinMercedes.js
                            SummarySerie.js
                            SummarySonder.js
                            SummaryKonditionen.js
                            SummaryLeistungsdaten.js
                            SummaryReifenlabel.js
                            SummaryVerbrauchsdaten.js
                                ConsumptionLabel.js
                            ElementSearch.js
                            EmailSummary.js
                            Mietumfang.js
    */
